spring:
  application:
    name: M-USER
#  redis:
#    host: 10.0.0.106
#    port: 6379
#    database: 0
#    jedis:
#      pool:
#        max-active: 20
#        max-idle: 10
#        max-wait: 1000


server:
  port: 1003


